matrix:
  include:
    - stage: deploy
      language: ruby
      rvm:
        - 2.4.0
      name: Deploy
      before_script:
        - bundle install
      script: "./deploy.sh"
      if: branch IN (master, autodeploy) AND type = push
